name: kimchi
description: Kimchi is a super lightweight framework for state management based on Riverpod.
version: 0.0.4
repository: https://github.com/timcreatedit/kimchi

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.14.0+3
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
